version: '3.8'

services:
  db_server:
    build: ./db_server
    container_name: db_server
    ports:
      - "8000:8000"
    volumes:
      - ./db_server:/app
    environment:
      - DJANGO_SETTINGS_MODULE=db_server.settings

  shop_client:
    build: ./shop_client
    container_name: shop_client
    ports:
      - "8001:8001"
    volumes:
      - ./shop_client:/app
    environment:
      - DJANGO_SETTINGS_MODULE=shop_client.settings
    depends_on:
      - db_server